// One-shot SFX playback for the 9 clips under public/audio/, generated by
// tools/gen_sfx.py (procedural synthesis — see docs/genai-log.md for why,
// not a GenAI audio model: AudioGen's weights are CC-BY-NC, incompatible
// with this repo's MIT license). Plain HTMLAudioElement rather than the Web
// Audio API — these are short, independent one-shots with no mixing/effects
// need, and a fresh Audio() instance per call lets two overlapping triggers
// (e.g. two pickups a frame apart) both actually play instead of the second
// cutting the first off.

export type SfxName =
  | 'pickup'
  | 'hit'
  | 'timer-low'
  | 'energy-empty'
  | 'voxxy-shortcircuit'
  | 'droid-thud'
  | 'droid-getup'
  | 'biggy-fall';

const DEFAULT_VOLUME = 0.55;

/**
 * Fire-and-forget playback. `play()` returns a Promise that rejects if the
 * browser blocks it (no user gesture registered yet, tab backgrounded, etc.)
 * — never let that surface as an unhandled rejection, same tolerance this
 * project already gives other best-effort browser APIs (clipboard writes,
 * localStorage).
 */
export function playSfx(name: SfxName, volume = DEFAULT_VOLUME): void {
  const audio = new Audio(`/audio/${name}.wav`);
  audio.volume = volume;
  audio.play().catch(() => {});
}
